# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:6.11.1 #LTS

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - repo-yarn-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - repo-yarn-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.yarn-cache
          key: repo-yarn-{{ checksum "yarn.lock" }}

      # Run validation checks & generate coverage reports
      - run: yarn start validate.withCoverage

      # Run build script
      - run: yarn build

      # Send coverage report to Codecov
      - run: yarn start reportCoverage

      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_test_results:
          path: ./coverage/clover.xml

